### PR TITLE
srobertp/addVarDensityPSBDF1:  First implementation of the bdf1 algorithm

### PR DESCRIPTION
**Pull request by srobertp**
The base algorithm is implemented and runs with parun but needs to be tested more to ensure accuracy.  The post processing on the third model (pressure increment) needs to be further tested and we need to decide what to use for velocity_last in the velocity model when using the post processing.  Should we use  the post processed velocity or the un processed velocity?  

solves #31 

There is still some work to be done before we can merge and close this branch, but I wanted to set up this pull request as a location to discuss the progress of this work.

The algorithm without post processing should give first order convergence on every norm as computed by L2_Batch.py and still needs to be tested.  

Likewise, we need to test the boundary conditions for the third model.  Currently a flag called 'fixed' has been set on one of the dofs on the boundary.  The dirichlet conditions are set to 0 for that dof only.  this allows us to solve the laplacian system with 0 neumann boundary conditions.  The postStep() function then adjusts the mean value to be 0.  We need to test this more fully to make sure it is behaving the way we want it to.

### CODE REVIEW

**Comment by srobertp** [comment]
@cekees and @mfarthin You will be able to contribute to this pull request,  I thought I would centralize the discussion and decisions to be kept track of here.

**Comment by srobertp** [comment]
@cekees Do you think we should merge this branch srobertp/addVarDensityPSBDF1  into master so that we can make addition branches off of master instead of off of it? I think it is time to get master back up to date.  The original intention of this branch has been fulfilled even though we are still debugging it.  The fact that the bdf2 and parallelization parts have also been added has gone beyond the intention of the branch.  What do you think ?

**Comment by cekees** [comment]
I think you're right that we should go ahead and get master caught up.  It looks like you may need to do a merge by hand due to conflicts between this branch and master.

**Comment by srobertp** [comment]
I will do the merge by hand.  I think the conflicts  have to do with the latex report/ stuff but I will mash it all together.  I also committed a change that I had to fix with another couple commits to change the density equation.  I think for now we will leave it in flux form rho_t + div( rho u) = 0  instead of moving the bdf2 to hamiltonian format  rho_t + u dot grad_rho =0   as per the jcp 2009 paper.

**Pull request merged**
