### PR TITLE
[2nd order in u,v] added timeIntegration calculation in postStep; implicit velocity

### PR DESCRIPTION
**Pull request by cekees**
There was (at least) one more thing to do in postStep after we modify the solution, which is to re-evaluate the history in the timeIntegration.  I also turned off velocity extrapolation, but it may be that the extrapolation is working fine.  Couple of things to try and check that we don't loose the 2nd order convergence
- turn velocity extrapolation back on
- turn off analytical velocity solution in density
- check code for any other hacks
- re-enable non-analytical startup for first step

Here are the results  run with this commit over three refinements of DT (looks quadratic in rho and u). 

```
DT=0.05
rho
t= 1; error_u_L2[0][0]= 0.0020981;
u
t= 1; error_u_L2[0][0]= 0.000992537;
t= 1; error_u_H1[0][0]= 0.00605491;
v
t= 1; error_u_L2[1][0]= 0.00109142;
t= 1; error_u_H1[1][0]= 0.00638339;
p
t= 1; error_u_L2[0][0]= 0.0100527;
===
DT=0.025
rho
t= 1; error_u_L2[0][0]= 0.000527404;
u
t= 1; error_u_L2[0][0]= 0.000235266;
t= 1; error_u_H1[0][0]= 0.00194571;
v
t= 1; error_u_L2[1][0]= 0.000260666;
t= 1; error_u_H1[1][0]= 0.00201021;
p
t= 1; error_u_L2[0][0]= 0.00301679;
===
DT=0.0125
rho
t= 1; error_u_L2[0][0]= 0.000132081;
u
t= 1; error_u_L2[0][0]= 5.75997e-05;
t= 1; error_u_H1[0][0]= 0.000675337;
v
t= 1; error_u_L2[1][0]= 6.40324e-05;
t= 1; error_u_H1[1][0]= 0.00068726;
p
t= 1; error_u_L2[0][0]= 0.00100251;
```

### CODE REVIEW

**Comment by cekees** [comment]
worked on history stuff. This looks quadratic in velocity but not density. I tested with stabilization but it looks pretty bad.

```
t= 1; error_u_L2[0][0]= 0.710657;
[     152] Closing solution archive for navierstokes_vardensity_DT_0_050000_BDF2_p
[     152] Closing Archive
[     152] Done Closing Archive
[     154] 
t= 1; error_u_L2[0][0]= 0.000983645;
[     162] 
t= 1; error_u_H1[0][0]= 0.00630232;
[     164] 
t= 1; error_u_L2[1][0]= 0.00112469;
[     171] 
t= 1; error_u_H1[1][0]= 0.00672883;
[     174] 
t= 1; error_u_L2[0][0]= 0.0108754;
[

t= 1; error_u_L2[0][0]= 0.377959;
[     311] Closing solution archive for navierstokes_vardensity_DT_0_025000_BDF2_p
[     311] Closing Archive
[     312] Done Closing Archive
[     313] 
t= 1; error_u_L2[0][0]= 0.000241477;
[     320] 
t= 1; error_u_H1[0][0]= 0.00221123;
[     322] 
t= 1; error_u_L2[1][0]= 0.000287999;
[     329] 
t= 1; error_u_H1[1][0]= 0.00240683;
[     331] 
t= 1; error_u_L2[0][0]= 0.00367625;
```

**Comment by srobertp** [comment]
@cekees  I am wondering about the placement of the copying of terms to _lastlast and _last  in the postStep function. 

I am thinking that on a given time step 't',  we want to have

u = value at 't'
u_last  = value at tLast
u_lastlast = value at tLastLast

so starting the new time step, we need to shift u to u_last and u_lastlast to u_last  to make room for solving the new value u.  It seems to me that this needs to be done before the solution of 'u' hence the preStep.  I am not sure that this is maintained when we put the adjustment in the postStep function.  

One of the only troubles with it in the preStep is when we are using values from the previous timeStep that haven't been shifted yet (say we are in density and are using velocity, we need to extract the current velocity 'vel' and the previous velocity 'vel_last' but call them respectively 'vel_last' and 'vel_lastlast' since they are in the new time step and in that frame of reference have the names given above.  But I don't see a way around this unless we can shift them all simultaneuously at the beginning of the new time step.

What do you think?

**Comment by cekees** [comment]
I agree we should ensure that when stepping to t_n we have

u = value at 't_n'
u_last = value at tLast = 't_{n-1}'
u_lastlast = value at tLastLast = 't_{n-2}'

We are kind of abusing the pre and post step functions to do history for the time stepping, so I agree that this is tricky. Maybe what we should do is first take the history updating out of pre and post step functions and make it a separate member function, say updateHistory().  Then in only one of the model's preStep or postStep we call all of those updateHistory functions. I think you could do it in either the pressure model postStep or the density preStep though the initial steps will be tricky either way.  Seems like one usually needs and initializeHistory() and a updateHistory().

**Comment by srobertp** [comment]
@cekees  Commit 26accf327ae0f245ec1328fb2fa1d4927048c1bd changes the history manipulation to an external function.  I implemented a class that is initialized in the attachModel function of our first model (density) that takes the modelList parameter and then adjusts things properly.  I wanted to somehow have the "what to change" set locally in each class but I wasn't sure how to build something that could reach into each of those classes and call a local initializeHistory() function and updateHistory() function.  This works for now but if you have any ideas on how to restore that to local functions and decisions, please let me know.   

It is still the same problem with density being first order and large errors but the other models getting almost the correct rates and smaller errors.  So there is still something else going on.

**Pull request closed without merging**
